/**
 * Regenerates src/data/songs.ts and src/assets images from the uma.guide Grand Concert guide.
 *
 * Run with `npm run scrape`. Every field is parsed out of the page markup, so a layout
 * change upstream throws instead of silently producing wrong costs.
 */
import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const SOURCE = 'https://uma.guide/guides/grand-concert'

/** Cost icon id -> Performance Point token. `_04` is unused by the game. */
const TOKEN = { '00': 'dance', '01': 'passion', '02': 'vocal', '03': 'visual', '05': 'composure' }

/** Section heading -> the stage at which those songs become purchasable. */
const SECTIONS = [
  ['Songs available from the start', 'start'],
  ['These Songs are available after the first Concert', 'concert1'],
  ['These Songs are available after the second Concert', 'concert2'],
  ['These Songs are available after the third Concert', 'concert3'],
  ['These special Songs are awarded at specific times during a career', 'awarded'],
]

const decode = (s) =>
  s
    .replace(/<br\s*\/?>/g, ' ')
    .replace(/<[^>]+>/g, '')
    .replace(/&#39;/g, "'")
    .replace(/&amp;/g, '&')
    .replace(/&quot;/g, '"')
    .replace(/&nbsp;/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()

function parseSongs(html) {
  const songs = []

  for (const [heading, stage] of SECTIONS) {
    const headingIndex = html.indexOf(heading)
    if (headingIndex < 0) throw new Error(`Heading vanished from the guide: ${heading}`)

    const bodyStart = html.indexOf('<tbody>', headingIndex)
    const bodyEnd = html.indexOf('</tbody>', bodyStart)
    if (bodyStart < 0 || bodyEnd < 0) throw new Error(`No table follows heading: ${heading}`)

    for (const row of html.slice(bodyStart, bodyEnd).matchAll(/<tr>(.*?)<\/tr>/gs)) {
      const cells = [...row[1].matchAll(/<td[^>]*>(.*?)<\/td>/gs)].map((m) => m[1])
      if (cells.length < 5) throw new Error(`Row under "${heading}" has ${cells.length} cells`)

      // The awarded table swaps the Cost/Priority columns for a single "Gained at" column.
      const awarded = stage === 'awarded'
      const image = cells[0].match(/src="([^"]+)"/)
      if (!image) throw new Error(`Row under "${heading}" has no cover image`)

      const id = image[1].match(/(gc_\d+_[a-z]+)\.webp/)
      if (!id) throw new Error(`Unrecognised cover filename: ${image[1]}`)

      const name = decode(cells[1])
      const costCell = awarded ? '' : cells[4]
      const cost = {}
      for (const m of costCell.matchAll(/(\d+)\s*<img[^>]*utx_ico_performance_s_(\d\d)\.png/g)) {
        const token = TOKEN[m[2]]
        if (!token) throw new Error(`Unknown cost token "${m[2]}" on ${name}`)
        if (token in cost) throw new Error(`Duplicate cost token "${token}" on ${name}`)
        cost[token] = Number(m[1])
      }
      if (!awarded && Object.keys(cost).length === 0) {
        throw new Error(`Failed to parse a cost for ${name}: ${decode(costCell)}`)
      }

      songs.push({
        id: id[1],
        name,
        stage,
        cost,
        mastery: decode(cells[2]),
        concert: decode(cells[3]),
        gainedAt: awarded ? decode(cells[4]) : null,
        priority: awarded ? null : decode(cells[5] ?? ''),
        imagePath: image[1],
      })
    }
  }

  if (songs.length !== 23) throw new Error(`Expected 23 songs, parsed ${songs.length}`)
  return songs
}

async function download(url, destination) {
  const response = await fetch(url)
  if (!response.ok) throw new Error(`${response.status} fetching ${url}`)
  await mkdir(dirname(destination), { recursive: true })
  await writeFile(destination, Buffer.from(await response.arrayBuffer()))
}

function renderModule(songs) {
  const entries = songs
    .map((song) => {
      const cost = Object.entries(song.cost)
        .map(([token, amount]) => `${token}: ${amount}`)
        .join(', ')
      return [
        '  {',
        `    id: '${song.id}',`,
        `    name: ${JSON.stringify(song.name)},`,
        `    stage: '${song.stage}',`,
        `    cost: { ${cost} },`,
        `    mastery: ${JSON.stringify(song.mastery)},`,
        `    concert: ${JSON.stringify(song.concert)},`,
        `    gainedAt: ${song.gainedAt === null ? 'null' : JSON.stringify(song.gainedAt)},`,
        `    priority: ${song.priority === null ? 'null' : JSON.stringify(song.priority)},`,
        '  },',
      ].join('\n')
    })
    .join('\n')

  return [
    `// Generated by scripts/scrape-songs.mjs from ${SOURCE}. Do not edit by hand.`,
    "import type { Song } from '../types'",
    '',
    'export const SONGS: readonly Song[] = [',
    entries,
    ']',
    '',
  ].join('\n')
}

const html = await fetch(SOURCE).then((r) => {
  if (!r.ok) throw new Error(`${r.status} fetching the guide`)
  return r.text()
})

const songs = parseSongs(html)

await Promise.all([
  ...songs.map((song) => download(`https://uma.guide${song.imagePath}`, `${ROOT}/src/assets/songs/${song.id}.webp`)),
  ...Object.keys(TOKEN).map((n) =>
    download(`https://uma.guide/icon/gl-tokens/utx_ico_performance_s_${n}.png`, `${ROOT}/src/assets/tokens/${n}.png`),
  ),
])

await writeFile(`${ROOT}/src/data/songs.ts`, renderModule(songs))
console.log(`Wrote ${songs.length} songs and ${songs.length + Object.keys(TOKEN).length} images.`)
